repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.4
    hooks:
      - id: ruff              # fast linter & fixer
        args: [--fix]         # auto-apply safe fixes
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black             # opinionated formatter
