name: CI

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install project in editable mode (+dev tools)
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e '.[dev]'
          python -m pip install coverage coveralls

      - name: Ruff lint
        run: ruff check .

      - name: Black formatting check
        run: black --check .

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage report -m

      - name: Upload coverage to Coveralls
        run: coveralls --service=github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
